---
- name: Create Ansible User with rights
  hosts: all
  become: true
  tasks:
    - name: Create Ansible user
      user:
        name: ansible
        comment: "User for Ansible Tower access"
        shell: /bin/bash
        system: yes

    - name: Create devops file
      file:
        path: /etc/sudoers.d/devops
        state: touch
        mode: 0644
      when:
        - ansible_distribution == "RedHat"
        - ansible_distribution_major_version > "5"

    - name: Create content in sudo file
      lineinfile:
        path: /etc/sudoers.d/devops
        line: 'ansible        ALL=(ALL)       NOPASSWD:ALL'
      when:
        - ansible_distribution == "RedHat"
        - ansible_distribution_major_version > "5"

    - name: Change devops file permission (RHEL6)
      file:
        path: /etc/sudoers.d/devops
        mode: 0440
      when:
        - ansible_distribution == "RedHat"
        - ansible_distribution_major_version == "6"

    - name: Create content in sudo file (RHEL 5)
      lineinfile:
        path: /etc/sudoers
        line: 'ansible        ALL=(ALL)       NOPASSWD:ALL'
      when:
        - ansible_distribution == "RedHat"
        - ansible_distribution_major_version == "5"

    - name: Create content in sudo file (RHEL6 and RHEL7)
      lineinfile:
        path: /etc/sudoers
        line: '#includedir /etc/sudoers.d'
      when:
        - ansible_distribution == "RedHat"
        - ansible_distribution_major_version >= "6"

    - name: Create .ssh directory
      file:
        path: /home/ansible/.ssh
        state: directory
        owner: ansible
        group: ansible
        mode: 0700

    - name: Create key file
      file:
        path: /home/ansible/.ssh/authorized_keys
        state: touch
        mode: 0600
        owner: ansible
        group: ansible

    - name: Create content in sudo file
      lineinfile:
        path: /home/ansible/.ssh/authorized_keys
        line: 'ssh-rsa AAAAB3NzaC1yc2EAAAddddddddddddfffffffffffffffffffffffffffffffffaaaaaaaaaaaaa'